----------------------------------------
-- MAGNITUDE ANALYSIS
----------------------------------------
/*

Magnitude analysis is to compare measure values by categories.
It helps us understand the importance of different categories

1. Total customers by country
2. Total customers by gender
3. Total products by category
4. Average cost in each category
5. Total revenue generated in each category
6. Total revenue generated by each customer
7. Distribution of solid items across countries
8. Total revenue generated by each country	
9. Total products sold by each country
10. Total Orders by each year
11. Total sold items in each year
12. Total items sold in each year by country

*/
----------------------------------------

-- Total customers by country

SELECT
Country,
COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY 2 DESC

-- Total customers by gender

SELECT
gender,
COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY 2 DESC

-- Total products by category

SELECT
category,
COUNT(product_key) As total_products
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC

-- Average cost in each category

SELECT
category,
AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Total revenue generated in each category

SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY 2 DESC

-- Total revenue generated by each customer

SELECT
c.customer_key,
CONCAT(c.first_name,' ',c.last_name) AS customer_name,
SUM(f.sales_amount) AS revenue_generated
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, CONCAT(c.first_name,' ',c.last_name)
ORDER BY 3 DESC

-- Distribution of solid items (quantity) across countries

SELECT
c.country,
SUM(f.quantity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY 2 DESC

-- Total revenue generated by each country

SELECT
c.country,
SUM(f.sales_amount) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY 2 DESC

/*
Here Country is a low cardinality dimension - as it has less distinctive values
Whereas customers is a high cardinality dimension - it has more distinctive values
*/

-- Total products sold by each country

SELECT
c.country,
COUNT(f.product_key) AS total_products_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY 2 DESC


-- Total Orders by each year

SELECT
YEAR(order_date) AS order_year,
COUNT(DISTINCT order_number) as total_orders
FROM gold.fact_sales
GROUP BY YEAR(order_date)
ORDER BY 2 DESC

-- Total sold items in each year

SELECT
YEAR(order_date) AS order_year,
SUM(quantity) AS total_items
FROM gold.fact_sales
GROUP BY YEAR(order_date)
ORDER BY 2 DESC

-- Total items sold in each year by country

SELECT
c.country,
YEAR(f.order_date) AS order_year,
SUM(f.quantity) AS total_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY YEAR(order_date),c.country
ORDER BY 1,2 DESC

----------------------------------------
-- LETS HEAD TO RANKING ANALYSIS NEXT
----------------------------------------
